# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OperatorFabric
description: >- # this means to ignore newlines until "baseurl:"
  A Smart Assistant for System Operators
baseurl: '' # the subpath of your site, e.g. /blog
url: "https://opfab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  opfab

footer_text: >
    Powered by <a href="https://jekyllrb.com/">Jekyll</a> and <a href="https://getbootstrap.com/">Bootstrap</a>
    </br>Copyright 2018-2020 Authors of <a href="https://github.com/opfab/opfab.github.io/">OperatorFabric documentation</a>.
    Unless otherwise indicated, content is licensed under <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">CC-BY-4.0</a>.
    <br/>The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation,
    please see our <a href="https://www.linuxfoundation.org/trademark-usage">Trademark Usage</a> page.
    Linux is a registered trademark of Linus Torvalds. <a href="https://www.linuxfoundation.org/privacy/">Privacy Policy</a> and
    <a href="https://www.linuxfoundation.org/terms/">Terms of Use</a>.

avatar: "/assets/img/logo_lfe_operatorfabric.png"
favicon: "/assets/img/favicon.ico"

sass:
  sass_dir: assets/css
# Needed to prevent the following error
# Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.css':
# File to import not found or unreadable: bootstrap/bootstrap.
# Load path: <repo_path>/vendor/bundle/ruby/2.5.0/gems/jekyll-theme-primer-0.5.4/_sass on line 1

# Site structure
archives_path: "/archives/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docker/
